# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d7a6b6de27b76c11e0599ed3adf603dbf9d6dae8706d85383563a78faf27092eb48b500a749ce634703595dd659814f627830af666f6164693e3810f73e8c2a

test:
  secret_key_base: 9506b2af0519957567b80c037f684fdf39faf1a9525c151396f11af246af63339816a6dd9b4efc35a1d1fbe09e00a3f91b7926a89a0ec2d8f68ccac734928cb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
